version: 1

formatters:
  brief:
    format: '%(message)s'
  simple:
    format: '[%(name)s] - %(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(funcName)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class : logging.StreamHandler
    level: INFO
    formatter: brief
    # stream  : ext://sys.stdout

  file:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: app.log
    maxBytes: 104857600
    backupCount: 5

loggers:
    development:
        level: DEBUG
        handlers: [console, file]
        propagate: no

    staging:
        level: INFO
        handlers: [console, file]
        propagate: no

    production:
        level: WARNING
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]